name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Lint
        run: golangci-lint run
      - name: Test
        run: go test -v -coverprofile=/tmp/coverage.out . && go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: /tmp/coverage.html
