name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test code
        run: go test -v ./...
